language: java
install:
  # Download dependencies with JDK 8 because Maven Central supports
  # TLS 1.2 only but OpenJDK 6 does not.
  - export ORIGINAL_JAVA_HOME=$JAVA_HOME
  - jdk_switcher use oraclejdk8
  - ./mvnw test -DskipTests
  # Delete all files created with JDK 8
  - ./mvnw clean
  # Build with JDK 6 because we build the artifacts that are published
  # to Maven Central with OpenJDK 6, too.
  - jdk_switcher use openjdk6
  # Run original install command but without GPG signing
  - ./mvnw install -DskipTests=true -Dgpg.skip=true
  # Restore desired JDK
  - export JAVA_HOME=$ORIGINAL_JAVA_HOME
addons:
  apt:
    packages:
      - openjdk-6-jdk
jdk:
  - openjdk11
  - openjdk10
  - oraclejdk9
  - oraclejdk8
  - openjdk7
  - openjdk6
